- name: Add the user 
  ansible.builtin.user:
    name: node_exporter
    group: node_exporter

- name: "install node exporter."
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: '0777'
    
- name: "add node exporter configuration."
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: "modify node exporter config"
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/node_exporter.service
    block: |
      [Unit]
      Description=Prometheus Node Exporter Service
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target


- name: "enable node_exporter service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes